name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Remplacez par le nom de la branche que vous utilisez, si ce n'est pas 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Remplacez par le chemin du dossier contenant vos fichiers HTML, si ce n'est pas la racine
